"use client";

import React from "react";
import "./privacyComponent.scss";

export default function PrivacyComponent() {
  return (
    <>
      <div className="container privacy-policy-page">
        <div className="row">
          <div className="col-12">
            <h1 className="text-light text-center mb-4">Privacy Policy</h1>

            <p className="text-light">
              This Privacy Policy describes Our policies and procedures on the
              collection, use and disclosure of Your information when You use the
              Service and tells You about Your privacy rights and how the law
              protects You.
            </p>
            <p className="text-light">
              We use Your Personal data to provide and improve the Service. By
              using the Service, You agree to the collection and use of
              information in accordance with this Privacy Policy.
            </p>

            <h2 className="subHeadPvcH2 text-light mt-4">
              Interpretation and Definitions
            </h2>
            <h3 className="subHeadPvc text-light">Interpretation</h3>
            <p className="text-light">
              The words of which the initial letter is capitalized have meanings
              defined under the following conditions. The following definitions
              shall have the same meaning regardless of whether they appear in
              singular or in plural.
            </p>

            <h3 className="text-light">Definitions</h3>
            <p className="text-light">For the purposes of this Privacy Policy:</p>
            <ul className="text-light">
              <li>
                <p>
                  <strong>Account</strong> means a unique account created for You
                  to access our Service or parts of our Service.
                </p>
              </li>
              <li>
                <p>
                  <strong>Company</strong> (referred to as either "the
                  Company", "We", "Us" or "Our" in this
                  Agreement) refers to Jaiswal Digital, Kaggadasapura.
                </p>
              </li>
              <li>
                <p>
                  <strong>Cookies</strong> are small files that are placed on Your
                  computer, mobile device or any other device by a website,
                  containing the details of Your browsing history on that website
                  among its many uses.
                </p>
              </li>
              <li>
                <p>
                  <strong>Country</strong> refers to: Karnataka, India
                </p>
              </li>
              <li>
                <p>
                  <strong>Device</strong> means any device that can access the
                  Service such as a computer, a cellphone or a digital tablet.
                </p>
              </li>
              <li>
                <p>
                  <strong>Personal Data</strong> is any information that relates
                  to an identified or identifiable individual.
                </p>
              </li>
              <li>
                <p>
                  <strong>Service</strong> refers to the Website.
                </p>
              </li>
              <li>
                <p>
                  <strong>Service Provider</strong> means any natural or legal
                  person who processes the data on behalf of the Company.
                </p>
              </li>
              <li>
                <p>
                  <strong>Third-party Social Media Service</strong> refers to any
                  website or any social network website through which a User can
                  log in or create an account to use the Service.
                </p>
              </li>
              <li>
                <p>
                  <strong>Usage Data</strong> refers to data collected
                  automatically, either generated by the use of the Service or
                  from the Service infrastructure itself.
                </p>
              </li>
              <li>
                <p>
                  <strong>Website</strong> refers to Jaiswal Digital, accessible
                  from <a href="https://jaiswaldigital.com/">https://jaiswaldigital.com/</a>
                </p>
              </li>
              <li>
                <p>
                  <strong>You</strong> means the individual accessing or using
                  the Service, or the company, or other legal entity on behalf of
                  which such individual is accessing or using the Service.
                </p>
              </li>
            </ul>

            <h2 className="subHeadPvcH2 text-light mt-4">
              Collecting and Using Your Personal Data
            </h2>
            <h3 className="subHeadPvc text-light">Types of Data Collected</h3>

            <h4 className="text-light">Personal Data</h4>
            <p className="text-light">
              While using Our Service, We may ask You to provide Us with certain
              personally identifiable information that can be used to contact or
              identify You. Personally identifiable information may include, but
              is not limited to:
            </p>
            <ul className="text-light">
              <li>
                <p>Email address</p>
              </li>
              <li>
                <p>First name and last name</p>
              </li>
              <li>
                <p>Phone number</p>
              </li>
              <li>
                <p>Address, State, Province, ZIP/Postal code, City</p>
              </li>
              <li>
                <p>Usage Data</p>
              </li>
            </ul>

            <h4 className="text-light">Usage Data</h4>
            <p className="text-light">
              Usage Data is collected automatically when using the Service.
            </p>
            <p className="text-light">
              Usage Data may include information such as Your Device&apos;s
              Internet Protocol address (e.g. IP address), browser type, browser
              version, the pages of our Service that You visit, the time and date
              of Your visit, the time spent on those pages, unique device
              identifiers and other diagnostic data.
            </p>

            <h3 className="text-light mt-4">Tracking Technologies and Cookies</h3>
            <p className="text-light">
              We use Cookies and similar tracking technologies to track the
              activity on Our Service and store certain information.
            </p>
            <p className="text-light">
              Cookies can be "Persistent" or "Session" Cookies.
              Persistent Cookies remain on Your personal computer or mobile
              device when You go offline, while Session Cookies are deleted as
              soon as You close Your web browser.
            </p>

            <h2 className="subHeadPvcH2 text-light mt-4">Disclosure of Your Personal Data</h2>

            <h3 className="text-light">Business Transactions</h3>
            <p className="text-light">
              If the Company is involved in a merger, acquisition or asset sale,
              Your Personal Data may be transferred.
            </p>

            <h3 className="text-light">Law enforcement</h3>
            <p className="text-light">
              Under certain circumstances, the Company may be required to disclose
              Your Personal Data if required to do so by law or in response to
              valid requests by public authorities.
            </p>

            <h3 className="text-light">Other legal requirements</h3>
            <p className="text-light">
              The Company may disclose Your Personal Data in the good faith belief
              that such action is necessary to:
            </p>
            <ul className="text-light">
              <li>Comply with a legal obligation</li>
              <li>Protect and defend the rights or property of the Company</li>
              <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
              <li>Protect the personal safety of Users of the Service or the public</li>
              <li>Protect against legal liability</li>
            </ul>

            <h3 className="text-light mt-4">Security of Your Personal Data</h3>
            <p className="text-light">
              The security of Your Personal Data is important to Us, but remember
              that no method of transmission over the Internet, or method of
              electronic storage is 100% secure. While We strive to use
              commercially acceptable means to protect Your Personal Data, We
              cannot guarantee its absolute security.
            </p>

            <h3 className="text-light mt-4">Children&apos;s Privacy</h3>
            <p className="text-light">
              Our Service does not address anyone under the age of 13. We do not
              knowingly collect personally identifiable information from anyone
              under the age of 13.
            </p>

            <h3 className="text-light mt-4">Links to Other Websites</h3>
            <p className="text-light">
              Our Service may contain links to other websites that are not
              operated by Us. If You click on a third party link, You will be
              directed to that third party&apos;s site.
            </p>

            <h3 className="text-light mt-4">Changes to this Privacy Policy</h3>
            <p className="text-light">
              We may update Our Privacy Policy from time to time. We will notify
              You of any changes by posting the new Privacy Policy on this page.
            </p>
          </div>
        </div>
      </div>
    </>
  );
}

