export interface ServicePrice { icon: string; title: string; price: string; unit?: string; description: string; features: string[]; note?: string; cta: string; }

export const servicePricing: ServicePrice[] = [
  { icon: 'bi bi-globe', title: 'Website Development', price: '\u20B915,000', description: 'Responsive, fast and SEO-friendly business websites designed to build credibility and generate enquiries.', features: ['Responsive Design', 'Modern UI/UX', 'Contact Form', 'Basic SEO', 'Google Analytics', 'Search Console', 'Speed Optimization'], cta: 'Get Website Quote' },
  { icon: 'bi bi-share', title: 'Social Media Management', price: '\u20B98,000', unit: '/ Month', description: 'Complete social media management to build your brand presence and consistently engage your audience.', features: ['Facebook & Instagram Management', 'Content Planning', 'Post Design', 'Caption Writing', 'Hashtag Strategy', 'Monthly Content Calendar', 'Performance Tracking'], cta: 'Start Social Media' },
  { icon: 'bi bi-search', title: 'SEO', price: '\u20B910,000', unit: '/ Month', description: 'Data-driven SEO strategies designed to improve Google visibility, organic traffic and search rankings.', features: ['Keyword Research', 'On-Page SEO', 'Technical SEO', 'Content Optimization', 'Backlink Strategy', 'Search Console Monitoring', 'Monthly Reporting'], cta: 'Improve My SEO' },
  { icon: 'bi bi-geo-alt', title: 'Local SEO', price: '\u20B94,000', unit: '/ Month', description: 'Improve your local search visibility and help nearby customers discover your business.', features: ['Google Business Profile Optimization', 'Local Keyword Research', 'Local Citations', 'NAP Optimization', 'Local Backlinks', 'Review Strategy', 'Google Maps Optimization'], cta: 'Grow Local' },
  { icon: 'bi bi-google', title: 'Google Ads', price: '\u20B95,000', unit: '/ Month', description: 'Performance-focused Google Ads campaigns designed to reach high-intent customers and generate qualified leads.', features: ['Campaign Setup', 'Keyword Research', 'Ad Copy', 'Conversion Tracking', 'Audience Targeting', 'Campaign Optimization', 'Performance Reporting'], note: 'Ad spend is separate.', cta: 'Run Google Ads' },
  { icon: 'bi bi-megaphone', title: 'Meta Ads', price: '\u20B94,000', unit: '/ Month', description: 'Facebook and Instagram advertising campaigns focused on brand awareness, leads and customer acquisition.', features: ['Campaign Setup', 'Audience Research', 'Ad Creative Strategy', 'Lead Generation Campaigns', 'Retargeting', 'Campaign Optimization', 'Performance Tracking'], note: 'Ad spend is separate.', cta: 'Run Meta Ads' },
  { icon: 'bi bi-palette', title: 'Graphic Designing', price: '\u20B9200', unit: '/ Design', description: 'Professional marketing creatives that strengthen your brand identity and attract attention across digital platforms.', features: ['Social Media Posts', 'Ad Creatives', 'Banners', 'Promotional Designs', 'Business Graphics', 'Brand Creatives'], cta: 'Design With Us' },
  { icon: 'bi bi-play-btn', title: 'Video Editing', price: '\u20B9500', unit: '/ Video', description: 'Engaging video editing for Reels, Shorts, advertisements and promotional business content.', features: ['Reels & Shorts', 'Promotional Videos', 'Social Media Videos', 'Text Animation', 'Transitions', 'Background Music', 'Basic Motion Graphics'], cta: 'Create My Video' },
];
